# Generated by Django 4.2.16 on 2024-10-09 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
        ('projects', '0002_alter_project_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Topic',
        ),
        migrations.AlterField(
            model_name='project',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='projects', to='topics.topic'),
        ),
    ]
